cms:
    resource: "@CMSBundle/Controller/"
    type:     annotation
    prefix:   /

entity:
    resource: "@EntityBundle/Controller/"
    type:     annotation
    prefix:   /

website:
    resource: "@WebsiteBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
